version: '3.8'
services:
  # 가벼운 기본 Jupyter
  jupyter:
    image: jupyter/pyspark-notebook:python-3.10
    container_name: iceberg-jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=iceberg
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    networks:
      - iceberg-net

networks:
  iceberg-net:
    driver: bridge
